chore(back-end): LFA feedback
Raymond-Osy/iReporter pull request #14
Opened 2018-12-06 20:04 UTC by Raymond-Osy

- Use a proper context as response for unknown routes
- Follow strict namings contained in challenge 2 project
- Date should be an interger
- Remove image from the request body
- Add more validations for routes
- Remove PUT request

2018-12-06 23:07 UTC, fob413 requested changes

2018-12-06 23:07 UTC, fob413 commented on server/controllers/redFlagsController.js
> +    const redFlag = redFlags.find(r => r.id === parseInt(req.params.id));
is `r` a good variable name? Please correct this and any other places where you might be using non-descriptive variable names.

2018-12-06 23:07 UTC, fob413 commented on server/controllers/redFlagsController.js
> +      message: 'Red-flags search was successful',
Please go over the product specification document. This `message` is not supposed to be here. Please correct this and other endpoints

2018-12-06 23:07 UTC, fob413 commented on server/controllers/redFlagsController.js
> +      return res.status(404).json({ status: 404, message: 'Red-flag with the given location was not found' });
This line is too long, please adjust it and any other similar long lines

2018-12-06 23:32 UTC, Raymond-Osy commented on server/controllers/redFlagsController.js
> +    const redFlag = redFlags.find(r => r.id === parseInt(req.params.id));
Noted and corrected, thanks.

2018-12-07 00:12 UTC, Raymond-Osy commented on server/controllers/redFlagsController.js
> +      message: 'Red-flags search was successful',
Noted and corrected

2018-12-07 00:15 UTC, Raymond-Osy commented on server/controllers/redFlagsController.js
> +      return res.status(404).json({ status: 404, message: 'Red-flag with the given location was not found' });
Noted and corrected

2018-12-07 00:16 UTC, Raymond-Osy commented on server/controllers/redFlagsController.js
> +    const redFlag = redFlags.find(r => r.id === parseInt(req.params.id));
Noted and corrected

2018-12-07 15:26 UTC, fob413 requested changes
Anything you're saving from the `req.body` must be trim'ed. Please correct this

2018-12-07 15:26 UTC, fob413 commented on server/middleware/validator.js
> +    if (!location || comment.trim() === '') {
is there a reason why you're checking `comment.trim()` twice?

2018-12-07 15:26 UTC, fob413 commented on server/middleware/validator.js
> +    if (!location || typeof (location) !== 'string') {
Is there a reason why you're not checking for `location.trim` here?

2018-12-07 15:26 UTC, fob413 commented on server/middleware/validator.js
> +    if (!comment || typeof (comment) !== 'string') {
is there a reason for not checking `comment.trim()` here?

2018-12-09 04:49 UTC, Raymond-Osy commented on server/middleware/validator.js
> +    if (!location || typeof (location) !== 'string') {
Noted and corrected

2018-12-09 04:50 UTC, Raymond-Osy commented on server/middleware/validator.js
> +    if (!location || comment.trim() === '') {
Noted and corrected

2018-12-09 04:50 UTC, Raymond-Osy commented on server/middleware/validator.js
> +    if (!comment || typeof (comment) !== 'string') {
Noted and corrected

2018-12-10 01:03 UTC, merged